name: Android Build

on:
  push:
    branches:
      - main
      - mobile_development

  pull_request:
    branches:
      - main
      - mobile_development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Install Dependencies
        run: yarn install

      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > android/app/epione-release.keystore

      - name: Grant Execute Permission
        run: chmod +x android/gradlew

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleRelease
